"""
Interview Feedback Schema

Represents the AI evaluation of a single interview answer.

Generated by the Answer Evaluation Agent.
"""

from typing import List

from pydantic import BaseModel, Field


class ScoreBreakdown(BaseModel):
    """
    Represents an individual evaluation metric.
    """

    score: float = Field(
        ...,
        ge=0,
        le=10,
        description="Score obtained."
    )

    max_score: float = Field(
        default=10,
        description="Maximum possible score."
    )

    feedback: str = Field(
        ...,
        description="Reasoning behind the assigned score."
    )


class InterviewFeedback(BaseModel):
    """
    Evaluation of a single interview answer.
    """

    technical: ScoreBreakdown = Field(
        ...,
        description="Technical correctness evaluation."
    )

    communication: ScoreBreakdown = Field(
        ...,
        description="Communication quality evaluation."
    )

    completeness: ScoreBreakdown = Field(
        ...,
        description="Completeness of the answer."
    )

    confidence: ScoreBreakdown = Field(
        ...,
        description="Confidence shown while answering."
    )

    overall: ScoreBreakdown = Field(
        ...,
        description="Overall evaluation."
    )

    strengths: List[str] = Field(
        default_factory=list,
        description="Strong points in the answer."
    )

    weaknesses: List[str] = Field(
        default_factory=list,
        description="Weaknesses identified."
    )

    missing_topics: List[str] = Field(
        default_factory=list,
        description="Important concepts that were not covered."
    )

    suggestions: List[str] = Field(
        default_factory=list,
        description="Suggestions for improvement."
    )

    followup_recommended: bool = Field(
        default=False,
        description="Whether another question should be asked on this topic."
    )

    interviewer_notes: str = Field(
        default="",
        description="Private notes for the interviewer."
    )