"""
Job Search Tool
Responsible for communicating with external job APIs.
This tool performs NO AI reasoning.
It simply fetches jobs and converts them into
our internal Job schema.
"""
from typing import List
import requests
from backend.config.settings import settings
from backend.schemas.job import Job

class JobSearchTool:
    """
    Fetch jobs from the JSearch API.

    Responsibilities:
    - Call external API
    - Handle HTTP errors
    - Convert API response into Job objects

    This class performs NO AI reasoning.
    """
    def __init__(self):
        self.base_url = "https://jsearch.p.rapidapi.com/search"
        self.headers = {
            "X-RapidAPI-Key": settings.RAPID_API_KEY,
            "X-RapidAPI-Host": "jsearch.p.rapidapi.com",
        }
    def search_jobs(
        self,
        query: str,
        country: str = "in",
        page: int = 1,
    ) -> List[Job]:
        """
        Search jobs using the JSearch API.

        Args:
            query: Search query generated by the AI Agent.
            location: Preferred job location.
            page: Page number.

        Returns:
            List[Job]
        """
        params = {
            "query": query,
            "page": page,
            "num_pages": 1,
            "country":country ,
        }
        try:
            response = requests.get(
                self.base_url,
                headers=self.headers,
                params=params,
                timeout=20,
            )
            response.raise_for_status()
            data = response.json()
            jobs = []
            for item in data.get("data", []):
                jobs.append(self._map_to_job(item))
            return jobs
        except requests.RequestException as e:
            raise RuntimeError(f"Job Search API Error: {e}")

    def _map_to_job(self, item: dict) -> Job:
        """
        Convert one API response item into
        our internal Job schema.
        """

        return Job(
            title=item.get("job_title", ""),
            company=item.get("employer_name", ""),
            location=item.get("job_location", ""),
            employment_type=item.get("job_employment_type"),
            experience=None,
            salary=item.get("job_salary_string"),
            skills=self._extract_skills(item),
            description=item.get("job_description", ""),
            apply_url=item.get("job_apply_link"),
            source=item.get("job_publisher", "Unknown"),
        )

    def _extract_skills(self, item: dict) -> List[str]:
        """
        Placeholder.

        JSearch does not return structured skills.
        In Phase 3 we will replace this with an
        AI/NLP based skill extraction pipeline.
        """

        return []