"""
ATS Report Schema

Represents the complete ATS analysis generated by the
Resume Analysis Agent.

The report combines:

1. Deterministic numerical ATS scoring
2. AI-generated qualitative resume analysis
"""

from typing import List

from pydantic import BaseModel, Field

from backend.ATS.schemas.candidate_level import (
    CandidateLevel,
)


class SectionScore(BaseModel):
    """
    Represents the score of an individual resume section.

    Example:

        score = 18
        max_score = 25

    For a non-applicable section, such as professional
    experience for a fresher:

        score = 0
        max_score = 0
    """

    score: float = Field(
        ...,
        description="Score obtained for the section.",
    )

    max_score: float = Field(
        ...,
        description="Maximum possible score for the section.",
    )


class ATSReport(BaseModel):
    """
    Complete ATS analysis report.

    Numerical scores are generated by ATSScoringService.

    Qualitative feedback is generated by
    ResumeAnalysisService.
    """

    # =========================================================
    # Candidate Level
    # =========================================================

    candidate_level: CandidateLevel = Field(
        ...,
        description=(
            "Candidate career level used to determine "
            "ATS scoring weights."
        ),
    )

    # =========================================================
    # Overall Score
    # =========================================================

    overall_score: float = Field(
        ...,
        ge=0,
        le=100,
        description="Overall ATS score out of 100.",
    )

    # =========================================================
    # Section Scores
    # =========================================================

    contact_information: SectionScore = Field(
        ...,
        description=(
            "Score for contact information."
        ),
    )

    education: SectionScore = Field(
        ...,
        description=(
            "Score for education section."
        ),
    )

    experience: SectionScore = Field(
        ...,
        description=(
            "Professional experience score. "
            "Not applicable for freshers."
        ),
    )

    projects: SectionScore = Field(
        ...,
        description=(
            "Score for technical projects."
        ),
    )

    skills: SectionScore = Field(
        ...,
        description=(
            "Score for technical skills."
        ),
    )

    certifications: SectionScore = Field(
        ...,
        description=(
            "Score for certifications."
        ),
    )

    formatting: SectionScore = Field(
        ...,
        description=(
            "Structural ATS compatibility score."
        ),
    )

    summary: SectionScore = Field(
        ...,
        description=(
            "Score for professional summary or objective."
        ),
    )

    # =========================================================
    # AI Qualitative Analysis
    # =========================================================

    strengths: List[str] = Field(
        default_factory=list,
        description=(
            "Strengths identified by the AI resume analysis."
        ),
    )

    weaknesses: List[str] = Field(
        default_factory=list,
        description=(
            "Weaknesses identified by the AI resume analysis."
        ),
    )

    missing_keywords: List[str] = Field(
        default_factory=list,
        description=(
            "Relevant keywords recommended by the AI analysis."
        ),
    )

    # =========================================================
    # Section Feedback
    # =========================================================

    formatting_feedback: List[str] = Field(
        default_factory=list,
    )

    education_feedback: List[str] = Field(
        default_factory=list,
    )

    experience_feedback: List[str] = Field(
        default_factory=list,
    )

    project_feedback: List[str] = Field(
        default_factory=list,
    )

    skills_feedback: List[str] = Field(
        default_factory=list,
    )

    # =========================================================
    # Recommendations
    # =========================================================

    recommendations: List[str] = Field(
        default_factory=list,
        description=(
            "Highest-impact resume improvement recommendations."
        ),
    )