import asyncio
import json
from typing import Any, TypedDict

from groq import AsyncGroq
from langgraph.graph import END, START, StateGraph

from backend.config.settings import settings
from backend.database.db import database
from backend.mcp.client import MCPClient


# STATE
class JobResearchState(TypedDict, total=False):
    user_id: str
    resume_id: str
    user_request: str

    messages: list[dict[str, Any]]
    tool_results: list[dict[str, Any]]

    research_complete: bool
    final_report: str

    # Runtime-only object. Never sent to Groq.
    _mcp_client: Any


# SYSTEM PROMPT
RESEARCH_SYSTEM_PROMPT = """
You are Placeko's Job Research Agent.

Your job is to research the user's already-generated personalized job
recommendations using MCP tools.

Do NOT write the final user-facing report yourself. A separate final-report
step will do that.

RULES:
- Never invent candidate skills, projects, experience, or certifications.
- Use MCP tools instead of guessing.
- Resume evidence is the source of truth.
- "resume_gap" means the resume contains no evidence. It does NOT mean
  the candidate definitely lacks the skill.
- Use the user's persisted recommended jobs as the job-market source.
- Do NOT perform a new external job search during this workflow.
- Do not repeat a tool call when the required information is already
  available.

BOUNDED RESEARCH WORKFLOW:

1. Call get_recommended_jobs once.
2. Inspect the returned recommended jobs and their requirements.
3. Call search_resume_evidence using combined requirements.
   Maximum two evidence searches.
4. Use persisted job_readiness data when it is available.
5. Do not call search_jobs during this research workflow.
6. Do not call get_job_details unless specifically required.
7. Stop once enough evidence has been collected.

Prefer combined evidence queries such as:
"Python FastAPI LLM RAG LangGraph backend"

Do not search individual skills one by one.

Do not invent an overall fit score.
"""


# FINAL REPORT PROMPT

FINAL_REPORT_PROMPT = """
You are Placeko's final Job Research Report writer.

Create a concise, complete report from ONLY the supplied research data.

Do not invent information and do not claim that a candidate has a skill
unless the supplied resume evidence supports it.

The jobs in the supplied data are already personalized recommendations
generated by Placeko's recommendation pipeline.

Use this structure:

# Job Research Report

## 1. Relevant opportunities

For each of the top relevant recommended jobs include:
- Job title — Company
- Location
- Why it is relevant based on the supplied job information and grounded
  candidate evidence

Use at most 5 jobs.

## 2. Candidate evidence

List concrete skills, projects, or experience supported by the resume
evidence.

Mention the relevant project when useful.

## 3. Gaps / unverified requirements

Use the persisted readiness information when available.

Separate:
- requirements for which the resume contains no evidence
- requirements explicitly supported by the resume
- candidate-confirmed requirements, if present

Never convert a resume gap into a claim that the candidate lacks the skill.

## 4. Practical next steps

Give 3–5 concrete actions based only on the observed requirements,
grounded evidence, and gaps.

Important:
- Do not invent salary, experience requirements, dates, or technologies.
- Do not create a numerical fit score.
- Do not claim a job is suitable merely because it appears in the
  recommendation list.
- Keep the report readable and complete.
- Prefer concise tables or bullets over long paragraphs.
"""



# GROQ CLIENT
groq_client = AsyncGroq(
    api_key=settings.GROQ_API_KEY
)



# GROQ TOOL SCHEMA

# User-specific IDs are injected by the runtime.
# The model does not control them.
GROQ_TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "get_recommended_jobs",
            "description": (
                "Retrieve the user's already-generated personalized "
                "job recommendations from Placeko."
            ),
            "parameters": {
                "type": "object",
                "properties": {},
                "required": [],
            },
        },
    },
]

# MCP RESULT PARSER

def _extract_mcp_result(result: Any) -> Any:
    """
    Extract MCP 2.x structured output first.

    Falls back to text content for compatibility with
    text-based MCP responses.
    """

    if result is None:
        return None

    if getattr(result, "is_error", False):
        return {
            "error": True,
            "message": "MCP tool returned an error.",
        }

    # MCP 2.x structured output
    structured_content = getattr(
        result,
        "structured_content",
        None,
    )

    if structured_content is not None:
        return structured_content

    # Fallback for text-based MCP responses
    content = getattr(
        result,
        "content",
        None,
    )

    if not content:
        return None

    text_parts = []

    for item in content:
        if hasattr(item, "text"):
            text_parts.append(item.text)

    if not text_parts:
        return None

    combined = "\n".join(text_parts)

    try:
        return json.loads(combined)
    except json.JSONDecodeError:
        return combined

# RESULT COMPACTION

def compact_recommended_jobs(result: Any) -> Any:
    """
    Keep only the information required by the research/report
    stages while preserving persisted readiness information.
    """

    if not isinstance(result, dict):
        return result

    jobs = result.get("jobs")

    if not isinstance(jobs, list):
        return result

    compact_jobs = []

    for job in jobs[:5]:

        if not isinstance(job, dict):
            continue

        skills = job.get("skills") or []

        if not isinstance(skills, list):
            skills = []

        compact_job = {
            "job_id": job.get("job_id"),
            "title": job.get("title"),
            "company": job.get("company"),
            "location": job.get("location"),
            "employment_type": job.get("employment_type"),
            "experience": job.get("experience"),
            "salary": job.get("salary"),
            "skills": skills[:15],
            "description": (
                job.get("description") or ""
            )[:900],
            "apply_url": job.get("apply_url"),
            "source": job.get("source"),
        }

        # Existing persisted readiness information.
        readiness = job.get("job_readiness")

        if isinstance(readiness, dict):

            readiness_copy = dict(readiness)

            requirements = readiness_copy.get(
                "requirements"
            )

            if isinstance(requirements, list):
                readiness_copy["requirements"] = (
                    requirements[:15]
                )

            compact_job["job_readiness"] = readiness_copy

        compact_jobs.append(compact_job)

    output = dict(result)
    output["jobs"] = compact_jobs

    return output


def compact_resume_evidence(result: Any) -> Any:
    if not isinstance(result, dict):
        return result

    output = dict(result)

    evidence = output.get("evidence")

    if isinstance(evidence, list):
        output["evidence"] = evidence[:10]

    return output


# DETERMINISTIC RESEARCH HELPERS

def _recommended_jobs_results(
    state: JobResearchState,
) -> list[dict[str, Any]]:

    for item in state.get(
        "tool_results",
        [],
    ):

        if (
            item.get("tool")
            == "get_recommended_jobs"
        ):

            result = item.get(
                "result"
            )

            if isinstance(result, dict):

                jobs = result.get(
                    "jobs"
                )

                if isinstance(jobs, list):
                    return jobs

    return []


def _build_evidence_query(
    jobs: list[dict[str, Any]],
) -> str:
    """
    Build one grounded resume-evidence query from the
    requirements of the persisted recommended jobs.
    """

    requirements: list[str] = []
    seen: set[str] = set()

    for job in jobs[:5]:

        # Job skills
        for skill in job.get(
            "skills",
            [],
        ) or []:

            if not isinstance(
                skill,
                str,
            ):
                continue

            value = skill.strip()
            key = value.lower()

            if value and key not in seen:

                seen.add(key)
                requirements.append(
                    value
                )

        # Readiness requirements
        readiness = job.get(
            "job_readiness"
        )

        if isinstance(
            readiness,
            dict,
        ):

            for requirement in readiness.get(
                "requirements",
                [],
            ) or []:

                if not isinstance(
                    requirement,
                    dict,
                ):
                    continue

                value = requirement.get(
                    "requirement"
                )

                if not isinstance(
                    value,
                    str,
                ):
                    continue

                value = value.strip()
                key = value.lower()

                if value and key not in seen:

                    seen.add(key)
                    requirements.append(
                        value
                    )

    # Keep the query bounded.
    preferred = [
        "Python",
        "FastAPI",
        "LLM",
        "RAG",
        "LangGraph",
        "LangChain",
        "PyTorch",
        "Machine Learning",
        "NLP",
        "Docker",
        "AWS",
    ]

    ordered: list[str] = []

    for item in preferred + requirements:

        if item.lower() not in {
            value.lower()
            for value in ordered
        }:
            ordered.append(item)

    return " ".join(
        ordered[:15]
    )



# EXECUTE MCP TOOL
async def execute_mcp_tool(
    client: MCPClient,
    tool_name: str,
    arguments: dict[str, Any],
) -> Any:

    print(
        f"\n[AGENT] Calling MCP tool: "
        f"{tool_name}"
    )

    print(
        f"[AGENT] Arguments: "
        f"{arguments}"
    )

    result = await client.call_tool(
        tool_name,
        arguments,
    )

    parsed = _extract_mcp_result(
        result
    )

    print(
        f"[AGENT] {tool_name} completed"
    )

    return parsed


# MODEL NODE — TOOL SELECTION ONLY

async def call_model(
    state: JobResearchState,
) -> dict[str, Any]:

    messages = list(
        state.get(
            "messages",
            [],
        )
    )

    if not any(
        message.get("role") == "system"
        for message in messages
    ):

        messages.insert(
            0,
            {
                "role": "system",
                "content": RESEARCH_SYSTEM_PROMPT,
            },
        )

    response = await groq_client.chat.completions.create(
        model=settings.GROQ_MODEL,
        messages=messages,
        tools=GROQ_TOOLS,
        tool_choice="auto",
        max_tokens=500,
    )

    message = response.choices[0].message

    assistant_message: dict[str, Any] = {
        "role": "assistant",
        "content": message.content or "",
    }

    if message.tool_calls:

        assistant_message["tool_calls"] = []

        for tool_call in message.tool_calls:

            assistant_message[
                "tool_calls"
            ].append(
                {
                    "id": tool_call.id,
                    "type": "function",
                    "function": {
                        "name": (
                            tool_call.function.name
                        ),
                        "arguments": (
                            tool_call.function.arguments
                        ),
                    },
                }
            )

    messages.append(
        assistant_message
    )

    return {
        "messages": messages,
    }



# TOOL NODE

async def execute_tools(
    state: JobResearchState,
) -> dict[str, Any]:
    """
    Execute the bounded research workflow.

    Research source:
        persisted recommended jobs

    Additional evidence:
        grounded resume evidence
    """

    messages = list(
        state.get(
            "messages",
            [],
        )
    )

    tool_results = list(
        state.get(
            "tool_results",
            [],
        )
    )

   
    # MCP CLIENT

    client = state.get(
        "_mcp_client"
    )

    owns_client = False

    if client is None:

        client = MCPClient()

        await client.connect()

        owns_client = True

        print(
            "\n[AGENT] MCP CLIENT CONNECTED "
            "(research node)"
        )

    
    # MODEL TOOL CALL
    last_message = (
        messages[-1]
        if messages
        else {}
    )

    tool_calls = last_message.get(
        "tool_calls",
        [],
    )

    recommendation_call = next(
        (
            call
            for call in tool_calls
            if call["function"]["name"]
            == "get_recommended_jobs"
        ),
        None,
    )

    if recommendation_call is None:

        if owns_client:
            await client.close()

        return {
            "messages": messages,
            "tool_results": tool_results,
            "research_complete": True,
        }

    
    # 1. GET PERSISTED RECOMMENDATIONS
  
    recommendation_arguments = {
        "user_id": state["user_id"],
        "resume_id": state["resume_id"],
    }

    recommendation_result = await execute_mcp_tool(
        client,
        "get_recommended_jobs",
        recommendation_arguments,
    )

    recommendation_result = (
        compact_recommended_jobs(
            recommendation_result
        )
    )

    tool_results.append(
        {
            "tool": "get_recommended_jobs",
            "arguments": recommendation_arguments,
            "result": recommendation_result,
        }
    )

    messages.append(
        {
            "role": "tool",
            "tool_call_id": recommendation_call["id"],
            "name": "get_recommended_jobs",
            "content": json.dumps(
                recommendation_result,
                default=str,
            ),
        }
    )

    jobs = []

    if isinstance(
        recommendation_result,
        dict,
    ):

        jobs = recommendation_result.get(
            "jobs",
            [],
        )

    if not isinstance(
        jobs,
        list,
    ):
        jobs = []

   
    # 2. GROUNDED RESUME EVIDENCE
    evidence_query = _build_evidence_query(
        jobs
    )

    if evidence_query:

        evidence_arguments = {
            "user_id": state["user_id"],
            "resume_id": state["resume_id"],
            "query": evidence_query,
        }

        evidence_result = await execute_mcp_tool(
            client,
            "search_resume_evidence",
            evidence_arguments,
        )

        evidence_result = (
            compact_resume_evidence(
                evidence_result
            )
        )

        tool_results.append(
            {
                "tool": "search_resume_evidence",
                "arguments": evidence_arguments,
                "result": evidence_result,
            }
        )

   
    # NO MORE MCP CALLS

    # The recommendation jobs already contain persisted
    # readiness information. Therefore we do not call
    # analyze_fresh_job_readiness here.

    if owns_client:

        await client.close()

        print(
            "[AGENT] MCP CLIENT DISCONNECTED "
            "(research node)"
        )

    return {
        "messages": messages,
        "tool_results": tool_results,
        "research_complete": True,
    }



# FINAL REPORT CONTEXT

def build_final_context(
    state: JobResearchState,
) -> str:

    compact_results = []

    for item in state.get(
        "tool_results",
        [],
    ):

        tool_name = item.get(
            "tool"
        )

        result = item.get(
            "result"
        )

        if tool_name == "get_recommended_jobs":

            result = compact_recommended_jobs(
                result
            )

        elif tool_name == "search_resume_evidence":

            result = compact_resume_evidence(
                result
            )

        compact_results.append(
            {
                "tool": tool_name,
                "result": result,
            }
        )

    serialized = json.dumps(
        compact_results,
        ensure_ascii=False,
        default=str,
    )

    return serialized[:14000]

# FINAL REPORT NODE — NO TOOLS

async def generate_final_report(
    state: JobResearchState,
) -> dict[str, Any]:

    context = build_final_context(
        state
    )

    final_messages = [
        {
            "role": "system",
            "content": FINAL_REPORT_PROMPT,
        },
        {
            "role": "user",
            "content": (
                f"User request:\n"
                f"{state['user_request']}\n\n"
                "Research data from Placeko MCP tools:\n"
                f"{context}"
            ),
        },
    ]

    try:

        response = await groq_client.chat.completions.create(
            model=settings.GROQ_MODEL,
            messages=final_messages,
            max_tokens=900,
            temperature=0.2,
        )

        report = (
            response.choices[0].message.content
            or "No final report generated."
        )

    except Exception as error:

      
        # Deterministic fallback for Groq rate limits
       
        if (
            "429" not in str(error)
            and "rate limit"
            not in str(error).lower()
        ):
            raise

        jobs = []
        evidence = None

        for item in state.get(
            "tool_results",
            [],
        ):

            if item.get(
                "tool"
            ) == "get_recommended_jobs":

                result = item.get(
                    "result"
                )

                if isinstance(
                    result,
                    dict,
                ):
                    jobs = (
                        result.get(
                            "jobs",
                            [],
                        )
                        or []
                    )

            elif item.get(
                "tool"
            ) == "search_resume_evidence":

                evidence = item.get(
                    "result"
                )

        lines = [
            "# Job Research Report",
            "",
            "## 1. Relevant opportunities",
        ]

        if jobs:

            for job in jobs[:5]:

                lines.append(
                    f"- "
                    f"{job.get('title', 'Unknown role')} — "
                    f"{job.get('company', 'Unknown company')} "
                    f"("
                    f"{job.get('location', 'Location not provided')}"
                    f")"
                )

        else:

            lines.append(
                "- No persisted job recommendations were found."
            )

        lines.extend(
            [
                "",
                "## 2. Candidate evidence",
            ]
        )

        if (
            isinstance(
                evidence,
                dict,
            )
            and evidence.get(
                "evidence"
            )
        ):

            for item in evidence[
                "evidence"
            ][:10]:

                lines.append(
                    f"- "
                    f"{item.get('source_type', 'evidence')}: "
                    f"{item.get('source', 'Unknown')} — "
                    f"{item.get('matched_text', '')}"
                )

        else:

            lines.append(
                "- No matching grounded resume evidence was found."
            )

        lines.extend(
            [
                "",
                "## 3. Gaps / unverified requirements",
            ]
        )

        readiness_found = False

        for job in jobs[:5]:

            readiness = job.get(
                "job_readiness"
            )

            if not isinstance(
                readiness,
                dict,
            ):
                continue

            requirements = readiness.get(
                "requirements",
                [],
            )

            for requirement in requirements[:10]:

                readiness_found = True

                lines.append(
                    f"- "
                    f"{requirement.get('requirement', 'Requirement')}: "
                    f"{requirement.get('status', 'unverified')} — "
                    f"{requirement.get('explanation', '')}"
                )

        if not readiness_found:

            lines.append(
                "- Persisted readiness information was not available."
            )

        lines.extend(
            [
                "",
                "## 4. Practical next steps",
                "- Review the recommended jobs against the grounded resume evidence.",
                "- Address requirements marked as resume gaps or unverified.",
                "- Review the persisted readiness evidence before applying.",
            ]
        )

        report = "\n".join(
            lines
        )

    return {
        "final_report": report,
    }



# ROUTER

def route_after_model(
    state: JobResearchState,
) -> str:

    if state.get(
        "research_complete"
    ):
        return "final_report"

    messages = state.get(
        "messages",
        [],
    )

    if not messages:
        return "final_report"

    last_message = messages[-1]

    if last_message.get(
        "tool_calls"
    ):
        return "tools"

    return "final_report"



# GRAPH

def build_research_graph():

    graph = StateGraph(
        JobResearchState
    )

    graph.add_node(
        "model",
        call_model,
    )

    graph.add_node(
        "tools",
        execute_tools,
    )

    graph.add_node(
        "final_report",
        generate_final_report,
    )

    graph.add_edge(
        START,
        "model",
    )

    graph.add_conditional_edges(
        "model",
        route_after_model,
        {
            "tools": "tools",
            "final_report": "final_report",
        },
    )

    graph.add_conditional_edges(
        "tools",
        lambda state: (
            "final_report"
            if state.get(
                "research_complete"
            )
            else "model"
        ),
        {
            "model": "model",
            "final_report": "final_report",
        },
    )

    graph.add_edge(
        "final_report",
        END,
    )

    return graph.compile()

# TEST RUNNER


async def test_research_agent():

    if database.db is None:
        await database.connect_db()

    resume = await database.db[
        "resumes"
    ].find_one(
        {
            "is_active": True
        },
        sort=[
            (
                "created_at",
                -1,
            )
        ],
    )

    if not resume:
        raise RuntimeError(
            "No active resume found."
        )

    user_id = resume[
        "user_id"
    ]

    resume_id = str(
        resume["_id"]
    )

    print(
        "\nACTIVE RESUME"
    )

    print(
        f"user_id: {user_id}"
    )

    print(
        f"resume_id: {resume_id}"
    )

    print(
        f"file_name: {resume.get('file_name')}"
    )

    client = MCPClient()

    try:

        await client.connect()

        print(
            "\nMCP CLIENT CONNECTED"
        )

        graph = build_research_graph()

        user_request = (
            "Research my existing recommended jobs in India for "
            "AI/ML and backend engineering. Explain why the "
            "recommended opportunities are relevant and compare "
            "their requirements with grounded evidence from my resume."
        )

        initial_state: JobResearchState = {
            "user_id": user_id,
            "resume_id": resume_id,
            "user_request": user_request,
            "messages": [
                {
                    "role": "user",
                    "content": user_request,
                }
            ],
            "tool_results": [],
            "research_complete": False,
            "_mcp_client": client,
        }

        result = await graph.ainvoke(
            initial_state,
            config={
                "recursion_limit": 12
            },
        )

        print(
            "\n"
            + "=" * 70
        )

        print(
            "FINAL JOB RESEARCH REPORT"
        )

        print(
            "=" * 70
        )

        print(
            result.get(
                "final_report",
                "No final report generated.",
            )
        )

        print(
            "\n"
            + "=" * 70
        )

        print(
            "TOOLS USED"
        )

        print(
            "=" * 70
        )

        for item in result.get(
            "tool_results",
            [],
        ):

            print(
                f"- {item['tool']} "
                f"{json.dumps(item['arguments'], default=str)}"
            )

    finally:

        await client.close()

# ENTRY POINT
if __name__ == "__main__":
    asyncio.run(
        test_research_agent()
    )